name: Deploy to github pages
on:
  push:
      branches:
        - master
jobs:
  gh-pages-deploy:
    name: Deploying to gh-pages
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js for use with actions
        uses: actions/setup-node@v2
        with:
          node-version: 12.x

      - name: Checkout branch
        uses: actions/checkout@v2
        with: 
          path: gh-pages

      - name: Clean install dependencies
        run: npm update

      - name: lets find outdate packages
        run: npm outdated --depth=3

      - name: Run deploy script
        run: |
          git config user.name "kaa468" && git config user.email "1kanaya51@gmail.com"
          npm run gh-pages-deploy

      